/*
* Copyright (c) 2017,华阳通用电子有限公司，软件工程中心
* All rights reserved.
*
* 文件名称：hal_diagnosis.h
* 文件标识：
* 摘 要：   HAL故障码头文件
*
* 当前版本：2.0
* 作 者：   jczhang@foryouge.com.cn
* 完成日期：2017年4月27日
*/

#ifndef _HAL_DIA_ENUM_H
#define _HAL_DIA_ENUM_H

//定义各种故障码的头 固定不变 3条
typedef enum 
{ 	
	ENUM_HAL_HEAD_MCU	 	= 0xaa,    //mcu
	ENUM_HAL_HEAD_OS 		= 0xa0,    //os
	ENUM_HAL_HEAD_MPU	    = 0xa1     //mpu
}CONFIG_DIAGNOSIS_HEAD;

//定义各种故障码的值  可添加 
typedef enum 
{ 	
	ENUM_HAL_CODE_RV          = 0x01,   //倒车异常
	ENUM_HAL_CODE_USBSD       = 0x02,	//usb、sd异常
	ENUM_HAL_CODE_DIALOG      = 0x03,	//异常弹框
	ENUM_HAL_CODE_UI          = 0x04,   //UI异常
	ENUM_HAL_CODE_CRASH       = 0x05,   //死机
	ENUM_HAL_CODE_STRIKE      = 0x06,	//无法卡机
	ENUM_HAL_CODE_DATASAFE    = 0x07,	//数据安全
	
	//第二阶段添加新的(service)
	ENUM_HAL_CODE_APPMGR      = 0x21,	//AppMgr中间件异常 
	ENUM_HAL_CODE_SRCMGR      = 0x22,	//SrcMgr中间件异常 
	ENUM_HAL_CODE_AUDIOMGR    = 0x23,	//AudioMgr中间件异常 
	ENUM_HAL_CODE_CAMERA 	  = 0x25,	//Camera中间件异常
	ENUM_HAL_CODE_DEVMGR	  = 0x26,	//DevMgr中间件异常
	ENUM_HAL_CODE_DVR		  = 0x27,	//DVR中间件异常
	ENUM_HAL_CODE_KEY		  = 0x28,	//KEY中间件异常
	ENUM_HAL_CODE_DEVICECOMM  = 0x29,	//DEVICECOMM中间件异常
	ENUM_HAL_CODE_RADIO		  = 0x2A,	//RADIO中间件异常
	ENUM_HAL_CODE_SETTING	  = 0x2B,	//SETTING中间件异常
	ENUM_HAL_CODE_SYSTEM	  = 0x2C,	//SYSTEM中间件异常
	ENUM_HAL_CODE_UPDATE	  = 0x2D,	//UPDATE中间件异常
	ENUM_HAL_CODE_WIFI		  = 0x2F,	//WIFI中间件异常
	ENUM_HAL_CODE_CARLIFE 	  = 0x30,	//Carlife中间件异常
	//(app)
	ENUM_HAL_CODE_AUXAPP 	  = 0x41,	//AUX应用程序异常	
	ENUM_HAL_CODE_BTAPP   	  = 0x42,	//BT应用程序异常	
	ENUM_HAL_CODE_CARLIFEAPP  = 0x43,	//Carlife应用程序异常	
	ENUM_HAL_CODE_DVRAPP      = 0x44,	//DVR应用程序异常
	ENUM_HAL_CODE_FACTORY     = 0x45,	//Factory应用程序异常
	ENUM_HAL_CODE_HOME        = 0x46,	//Home应用程序异常
	ENUM_HAL_CODE_MUSICAPP    = 0x47,	//Music应用程序异常
	ENUM_HAL_CODE_VIDEOAPP    = 0x48,	//Video应用程序异常
	ENUM_HAL_CODE_PICTUREAPP  = 0x49,	//Picture应用程序异常
	ENUM_HAL_CODE_RADIOAPP    = 0x4A,	//Radio应用程序异常
	ENUM_HAL_CODE_SETTINGAPP  = 0x4b,	//Setting应用程序异常
	ENUM_HAL_CODE_OVERLAY     = 0x4c	//Overlay应用程序异常
	
	//....								//可添加
	
}CONFIG_DIAGNOSIS_CODE;


//定义各种故障码的值的参数  可添加
typedef enum   
{ 	
//倒车参数
	ENUM_HAL_VALUE_RV_ARM2_FAIL = 0x01,			
	ENUM_HAL_VALUE_RV_INIT_EMMC = 0x02,
	ENUM_HAL_VALUE_RV_NO_SIGNAL = 0x03,
	ENUM_HAL_VALUE_RV_VIDEO_CHANNEL = 0x04,
	//.... 
//usb、sd异常
	ENUM_HAL_VALUE_USB_CANNOT_RECOG = 0x01,
	ENUM_HAL_VALUE_USB_UNMOUNT = 0x02,
	ENUM_HAL_VALUE_SD_CANNOT_RECOG = 0x03,
	ENUM_HAL_VALUE_SD_UNMOUNT = 0x04,
	ENUM_HAL_VALUE_USBSD_VIDEO_PLAY_ABNOMAL = 0x05,
	ENUM_HAL_VALUE_USBSD_VIDEO_PLAY_BLACKSCREEN  = 0x06,
	ENUM_HAL_VALUE_SD_INSERT_TO_DIA  = 0x07,
	
//弹框异常
	ENUM_HAL_VALUE_DIALOG_SERVICE = 0x01,
	ENUM_HAL_VALUE_DIALOG_APP = 0x02,
	ENUM_HAL_VALUE_DIALOG_NAVIGATION = 0x03,
	ENUM_HAL_VALUE_DIALOG_INSUFFICIENT_MEMERY = 0x04,
	ENUM_HAL_VALUE_DIALOG_MANDATORY_WARMING = 0x05,
	
//UI显示异常
	ENUM_HAL_VALUE_UI_BUSINESS_LOGIC_ABNORMAL = 0x01,
	ENUM_HAL_VALUE_UI_DATE_CHANGED = 0x02,
	
//死机
	ENUM_HAL_VALUE_CRASH_TS_ABNORMAL = 0x01,
	ENUM_HAL_VALUE_CRASH_DRIVER_THREAD = 0x02,
	ENUM_HAL_VALUE_CRASH_THIRD_PARTY = 0x03,
	ENUM_HAL_VALUE_CRASH_CRYSTAL_ABNORMAL = 0x04,

//无法开机
	ENUM_HAL_VALUE_STRIKE_INIT_HANDSHAKE_FAIL = 0x01,
	ENUM_HAL_VALUE_STRIKE_LCD_FRAME = 0x02,
	ENUM_HAL_VALUE_STRIKE_FLASH = 0x03,
	ENUM_HAL_VALUE_STRIKE_CMU = 0x04,
	
//数据安全
	ENUM_HAL_VALUE_DATASAFE_LOST = 0x01,
	ENUM_HAL_VALUE_DATASAFE_CHECK_SELF = 0x02,
	
//(中间件)
//AppMgr中间件异常 
    ENUM_HAL_VALUE_APPMGR_RADIO_APP       	= 0x01,     //Radio App进程挂死
	ENUM_HAL_VALUE_APPMGR_USB_APP 			= 0x02,		//USB App进程挂死
	ENUM_HAL_VALUE_APPMGR_BT_APP 			= 0x03,		//BT App进程挂死
	ENUM_HAL_VALUE_APPMGR_AUX_APP 			= 0x04,		//AUX App进程挂死
	ENUM_HAL_VALUE_APPMGR_DVR_APP 			= 0x05,		//DVR App进程挂死
	ENUM_HAL_VALUE_APPMGR_CAMERA_APP 		= 0x06,		//Camera App进程挂死
	ENUM_HAL_VALUE_APPMGR_HOME_APP 			= 0x07,		//Home App进程挂死
	ENUM_HAL_VALUE_APPMGR_UPDATE_APP 		= 0x08,		//Update App进程挂死
	ENUM_HAL_VALUE_APPMGR_SETTING_APP 		= 0x09,		//Setting App进程挂死
	ENUM_HAL_VALUE_APPMGR_OVERLAY_APP 		= 0x0A,		//Overlay App进程挂死
	ENUM_HAL_VALUE_APPMGR_CALIFE_APP 		= 0x0B,		//Carlife App进程挂死
	ENUM_HAL_VALUE_APPMGR_FACTORY_APP 		= 0x0C,		//Factory App进程挂死
	ENUM_HAL_VALUE_APPMGR_MUSIC_APP 		= 0x0D,		//Music App进程挂死
	ENUM_HAL_VALUE_APPMGR_VIDEO_APP 		= 0x0E,		//Video App进程挂死
	ENUM_HAL_VALUE_APPMGR_PICTURE_APP 		= 0x0F,		//Picture App进程挂死
	ENUM_HAL_VALUE_APPMGR_RADIO_SERVICE 	= 0x10,		//Radio Service进程挂死
	ENUM_HAL_VALUE_APPMGR_USB_SERVICE 		= 0x11,		//USB Service进程挂死
	ENUM_HAL_VALUE_APPMGR_BT_SERVICE 		= 0x12,		//BT Service进程挂死
	ENUM_HAL_VALUE_APPMGR_CARLIFE_SERVICE 	= 0x13,		//Carlife Service进程挂死
	ENUM_HAL_VALUE_APPMGR_AUDIO_SERVICE 	= 0x14,		//AudioMgr Service进程挂死
	ENUM_HAL_VALUE_APPMGR_DEVICECOM_SERVICE = 0x15,		//DeviceCommon Service进程挂死
	ENUM_HAL_VALUE_APPMGR_DEVICEMGR_SERVICE = 0x16,		//DeviceMgr Service进程挂死
	ENUM_HAL_VALUE_APPMGR_SOURCEMGR_SERVICE = 0x17,		//SourceMgr Service进程挂死
	ENUM_HAL_VALUE_APPMGR_SYSTEM_SERVICE 	= 0x18,		//System Service进程挂死
	ENUM_HAL_VALUE_APPMGR_SCHEDULE_PROCESS 	= 0x19,		//进程调度失败
	ENUM_HAL_VALUE_APPMGR_WIFI_SERVICE 		= 0x1A,		//WiFiService进程挂死
	ENUM_HAL_VALUE_APPMGR_AUTOTEST_SERVICE	= 0x1B,		//Audotest Service进程挂死
	ENUM_HAL_VALUE_APPMGR_KEY_SERVICE	 	= 0x1C,		//Key Service进程挂死
	ENUM_HAL_VALUE_APPMGR_NOTIFY_SERVICE 	= 0x1D,		//Notify Service进程挂死
//SrcMgr中间件异常
	ENUM_HAL_VALUE_SRCMGR_WR_FILE_ABNORMAL 		= 0x01,		//写入文件异常
	ENUM_HAL_VALUE_SRCMGR_SWITCH_AUDIO_CHANNAL 	= 0x02,		//Audio通道是否切换
	ENUM_HAL_VALUE_SRCMGR_BT_STACK			 	= 0x03,		//BT 协议栈 Event ID
	ENUM_HAL_VALUE_SRCMGR_RD_FILE_ABNORMAL	 	= 0x04,		//读取文件异常
	ENUM_HAL_VALUE_SRCMGR_TRANSFER_INTERFACE 	= 0x05,		//记录是否调用协议栈Transfer接口
	ENUM_HAL_VALUE_SRCMGR_REARVIEW_STATUS	 	= 0x06,		//是否进入倒车状态
	ENUM_HAL_VALUE_SRCMGR_RECORD_S_S_EVENT_ID 	= 0x07,		//记录System Service Event ID
	ENUM_HAL_VALUE_SRCMGR_CONNECT_DEVMGR_FAIL 	= 0x08,		//Devicemgr连接失败
	ENUM_HAL_VALUE_SRCMGR_CONNECT_AUDIOMGR_FAIL = 0x09,		//Audiomgr连接失败
	ENUM_HAL_VALUE_SRCMGR_CONNECT_KEYSER_FAIL	= 0x0A,		//KeyService连接失败
	ENUM_HAL_VALUE_SRCMGR_CONNECT_SYS_SER_FAIL 	= 0x0B,		//SystemService连接失败
//AudioMgr中间件异常 
	ENUM_HAL_VALUE_AUDIOMGR_DBUS 				= 0x01,		//Dbus异常 Dbus实例化失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_CREATE_PIPE_FAIL	= 0x02,		//数据管道创建失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_READ_PIPE_FAIL 	    = 0x03,		//数据管道读取失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_WRITE_PIPE_FAIL 	= 0x04,		//数据管道写入失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_CREATE_DB_FAIL 		= 0x05,		//数据库文件创建失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_OPEN_DB_FAIL 		= 0x06,		//数据库文件打开失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_READ_DB_FAIL	 	= 0x07,		//数据库文件读取失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_WRITE_DB_FAIL 		= 0x08,		//数据库文件写入失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_CONNECT_PA_FAIL 	= 0x09,		//PA服务连接失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_GET_ADDR_FAIL 		= 0x0A,		//空间分配失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_OPEN_AUDIO_DEV_FAIL	= 0x0B,		//音频设备打开失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_AUDIO_DEV_INIT_FAIL = 0x0C,		//音频设备初始化失败，记录故障码
	ENUM_HAL_VALUE_AUDIOMGR_SET_AUDIO_DEV_FAIL 	= 0x0D,		//音频设备设定失败，记录故障码
//Camera中间件异常
	ENUM_HAL_VALUE_CAMERA_CHAT_ABNORMAL 		= 0x01,		//和devcom通信异常
//DevMgr中间件异常
	ENUM_HAL_VALUE_DEVMGR_CHAT_FAIL			= 0x01,			//Devmgr通信失败
	ENUM_HAL_VALUE_DEVMGR_CREATE_EVENT_FAIL	= 0x02,			//event创建失败
	ENUM_HAL_VALUE_DEVMGR_LIST_INIT_FAIL	= 0x03,			//列表初始化失败
//DVR中间件异常
	ENUM_HAL_VALUE_DVR_VIDEO_INIT_FAIL 		= 0x01,		//视频初始化失败
	ENUM_HAL_VALUE_DVR_CHAT_DVR_FAIL 		= 0x02,		//和DVR数据通信失败
	ENUM_HAL_VALUE_DVR_CHAT_DVR_WRONG_FAIL 	= 0x03,		//DVR通讯错误
	ENUM_HAL_VALUE_DVR_SD_FORMAT_FAIL 		= 0x04,		//SD卡格式化失败
	ENUM_HAL_VALUE_DVR_VIDEO_LOCKED_FAIL 	= 0x05,		//视频无法锁定
	ENUM_HAL_VALUE_DVR_SET_DVR_PARA_FAIL 	= 0x06,		//设置DVR参数失败
	ENUM_HAL_VALUE_DVR_FILE_ABNORMAL_FAIL 	= 0x07,		//文件异常
	ENUM_HAL_VALUE_DVR_FIVE_CHAT_DVR_FAIL 	= 0x08,		//连续5次收到DVR通讯错误
	ENUM_HAL_VALUE_DVR_RESET_SYSTEM_FAIL 	= 0x09,		//重设系统失败
//KEY中间件异常
	ENUM_HAL_VALUE_KEY_MEMERY_NOT_ENOUGH 		= 0x01,		//按键异常：内存分配不足
	ENUM_HAL_VALUE_KEY_PTHREAD_CRAETE_FAIL 		= 0x02,		//按键异常: 线程创建失败
	ENUM_HAL_VALUE_KEY_SERVER_FAIL 				= 0x03,		//按键异常: 通信服务端server失败
	ENUM_HAL_VALUE_KEY_SYSTEM_FAIL 				= 0x04,		//按键异常：连接System服务失败
	ENUM_HAL_VALUE_KEY_AUDIOMGR_FAIL 			= 0x05,		//按键异常：连接AudioMgr服务失败
	ENUM_HAL_VALUE_KEY_DEVICECOMM_FAIL 			= 0x06,		//按键异常：初始化Devcomm失败
	ENUM_HAL_VALUE_KEY_REARVIEW_STATUS_FAIL 	= 0x07,		//判断倒车状态失败
//DEVICECOMM中间件异常
	ENUM_HAL_VALUE_DEVICECOMM_TEN_SEC_FAIL			= 0x01,		//连续10s，MCU无回复
	ENUM_HAL_VALUE_DEVICECOMM_SHAKE_MCU_FAIL 		= 0x02,		//与MCU握手失败
	ENUM_HAL_VALUE_DEVICECOMM_THREE_MESG_FAIL 		= 0x03,		//重发3次消息给MCU都没回复
	ENUM_HAL_VALUE_DEVICECOMM_MCU_AUTHORITY_FAIL 	= 0x04,		//与MCU认证失败
//RADIO中间件异常
	ENUM_HAL_VALUE_RADIO_LOAD_STORE_FAIL 			= 0x01,		//存储加载失败
	ENUM_HAL_VALUE_RADIO_CREATE_G_DBUS_FAIL 		= 0x02,		//创建g_bus main loop线程失败
	ENUM_HAL_VALUE_RADIO_INIT_DEVICECOMM_FAIL 		= 0x03,		//初始化deviceComm失败
	ENUM_HAL_VALUE_RADIO_INIT_SYSTEM_FAIL 			= 0x04,		//初始化System线程失败
	ENUM_HAL_VALUE_RADIO_CREATE_NOTIFY_FAIL 		= 0x05,		//创建notify线程失败
	ENUM_HAL_VALUE_RADIO_READ_ZONE_FAIL 			= 0x06,		//读取地区失败
	ENUM_HAL_VALUE_RADIO_INPTHREAD_CREATE_FAIL 		= 0x07,		//内部处理线程创建失败
	ENUM_HAL_VALUE_RADIO_INDATA_CALL_MEMERY_FAIL 	= 0x08,		//内部数据申请内存失败
	ENUM_HAL_VALUE_RADIO_OPEN_DB_FAIL 				= 0x09,		//数据库打开异常
	ENUM_HAL_VALUE_RADIO_SAVE_DB_FAIL 				= 0x0A,		//数据库保存异常
	ENUM_HAL_VALUE_RADIO_UPDATE_TEMP_FILE_FAIL 		= 0x0B,		//临时文件更新异常
	ENUM_HAL_VALUE_RADIO_RUN_DEVCOM_CMD_FAIL 		= 0x0C,		//DeviceComm执行命令错误
	ENUM_HAL_VALUE_RADIO_RUN_DEVCOM_TO_FAIL 		= 0x0D,		//DeviceComm执行命令超时
	ENUM_HAL_VALUE_RADIO_MAX_TIME_RADIO_CMD_FAIL 	= 0x0E,		//Radio-cmd超过最大重试次数
	ENUM_HAL_VALUE_RADIO_APP_RUN_RADIO_CMD_FAIL 	= 0x0F,		//App执行错误Radio命令
	ENUM_HAL_VALUE_RADIO_DEVCOM_RUN_RDS_FAIL 		= 0x10,		//DeviceComm执行Rds命令错误
//SETTING中间件异常
	ENUM_HAL_VALUE_SETTING_LOAD_SAVE_FAIL 			= 0x01,		//存储加载失败
	ENUM_HAL_VALUE_SETTING_OPE_SAVE_FAIL 			= 0x02,		//存储操作失败
	ENUM_HAL_VALUE_SETTING_CREATE_NOTIFY_FAIL 		= 0x03,		//创建notify线程失败
	ENUM_HAL_VALUE_SETTING_SAVE_LANG_EMMC_FAIL 		= 0x04,		//设置语言到Emmc失败
//SYSTEM中间件异常
	ENUM_HAL_VALUE_SYSTEM_DB_INIT_FAIL 					= 0x01,		//数据库初始化失败
	ENUM_HAL_VALUE_SYSTEM_CREATE_SERVICE_PTHREAD_FAIL 	= 0x02,		//创建Server服务线程失败
	ENUM_HAL_VALUE_SYSTEM_MCOM_INIT_FAIL 				= 0x03,		//初始化MCOM失败
	ENUM_HAL_VALUE_SYSTEM_HARDKY_INIT_FAIL 				= 0x04,		//初始化hardkey失败
	ENUM_HAL_VALUE_SYSTEM_CREAT_NOTIFY_PTHREAD_FAIL 	= 0x05,		//创建notify线程失败
	ENUM_HAL_VALUE_SYSTEM_TS_INIT_FAIL 					= 0x06,		//初始化触摸屏异常
	ENUM_HAL_VALUE_SYSTEM_SET_TIME_MCU_TO_FAIL 			= 0x07,		//设置时间到MCU超时
	ENUM_HAL_VALUE_SYSTEM_FAC_MEDIA_FAIL 				= 0x08,		//恢复出厂设置媒体失败
	ENUM_HAL_VALUE_SYSTEM_FAC_BT_FAIL 					= 0x09,		//恢复出厂设置蓝牙失败
	ENUM_HAL_VALUE_SYSTEM_FAC_BL_FAIL 					= 0x0A,		//设置背光失败
	ENUM_HAL_VALUE_SYSTEM_FAC_TS_FAIL 					= 0x0B,		//设置屏幕触屏失败
	ENUM_HAL_VALUE_SYSTEM_FAC_GET_RV_STATUS_FAIL 		= 0x0C,		//取倒车状态失败

//UPDATE中间件异常
	ENUM_HAL_VALUE_UPDATE_APP_FAIL 					= 0x01,				//升级APP失败
	ENUM_HAL_VALUE_UPDATE_OS_FAIL 					= 0x02,				//升级OS失败
	ENUM_HAL_VALUE_UPDATE_MCU_FAIL 					= 0x03,				//升级MCU失败
	ENUM_HAL_VALUE_UPDATE_READ_CONFIG_INFO_FAIL 	= 0x04,				//配置信息读取失败
	ENUM_HAL_VALUE_UPDATE_FILE_RDWR_FAIL 			= 0x05,				//升级文件读写失败
	ENUM_HAL_VALUE_UPDATE_CHECK_FAIL 				= 0x06,				//升级包安全校验失败
//WIFI中间件异常
	ENUM_HAL_VALUE_WIFI_INSMOD_DRV_FAIL 			= 0x01,				//Wifi驱动加载失败
	ENUM_HAL_VALUE_WIFI_LOAD_SAVE_FAIL 				= 0x02,				//存储加载失败
	ENUM_HAL_VALUE_WIFI_CREATE_G_DBUS_FAIL 			= 0x03,				//创建g_bus main loop线程失败
	ENUM_HAL_VALUE_WIFI_CREATE_NOTIFY_FAIL 			= 0x04,				//创建notify线程失败
	ENUM_HAL_VALUE_WIFI_CHECK_CONNECT_STATUS_FAIL 	= 0x05,				//wifi检查连接状态的线程创建失败
	ENUM_HAL_VALUE_WIFI_WPA_CLI_FAIL 				= 0x06,				//wpa_cli执行控制命令失败
	ENUM_HAL_VALUE_WIFI_READ_FILE_FAIL 				= 0x07,				//读文件失败
	ENUM_HAL_VALUE_WIFI_SWITCH_DISCONTROL_FAIL 		= 0x08,				//wifi开关失效

//Carlife中间件异常							
	ENUM_HAL_VALUE_CARLIFE_G_BUS_MAIN_LOOP			= 0x01,			//g_bus main loop线程创建失败
	ENUM_HAL_VALUE_CARLIFE_DEVICE_DET 				= 0x02,			//设备检测线程创建失败
	ENUM_HAL_VALUE_CARLIFE_GET_VERSION_FAIL 		= 0x03,			//取得Andriod CarLife手机应用的版本失败
	ENUM_HAL_VALUE_CARLIFE_GET_H264_PPS_FAIL		= 0x04,			//申请CarLife的H.264的SPS和PPS的内存失败
	ENUM_HAL_VALUE_CARLIFE_RUN_ADB_FAIL				= 0x05,			//执行ADB命令失败
	ENUM_HAL_VALUE_CARLIFE_AUTHORITY_FAIL			= 0x06,	 		//Andriod设备授权失败
	ENUM_HAL_VALUE_CARLIFE_GET_ANDROID_OS_VER_FAIL	= 0x07,			//取得Andriod OS版本失败
	ENUM_HAL_VALUE_CARLIFE_RUN_BDIM_FAIL			= 0x08,			//运行bdim文件失败
	ENUM_HAL_VALUE_CARLIFE_ANDRIOD_CARLIFE_FAIL		= 0x09,			//启动Andriod手机 CarLife应用失败
	ENUM_HAL_VALUE_CARLIFE_RUN_BDSC_FAIL			= 0x0A,			//运行bdsc文件失败
	ENUM_HAL_VALUE_CARLIFE_SOC_CON_FAIL				= 0x0B,			//车机端和Andriod手机端Socket 连接失败
	ENUM_HAL_VALUE_CARLIFE_CAR_FORWARD_MOB_ONE		= 0x0C,			//车机端向手机端发送发车机端协议版本信息失败
	ENUM_HAL_VALUE_CARLIFE_CAR_FORWARD_MOB_TWO		= 0x0D,			//车机端向手机端发送发车机情报失败
	ENUM_HAL_VALUE_CARLIFE_CAR_FORWARD_MOB_THREE	= 0x0E,			//车机端向手机端发送统计信息失败
	ENUM_HAL_VALUE_CARLIFE_CAR_FORWARD_MOB_FOUR		= 0x0F,			//车机端向手机端发送video编码初始化情报失败
	ENUM_HAL_VALUE_CARLIFE_NOT_CARLIFE_UI			= 0x10,			//由于当前画面不是CarLife画面导致CarLife视频不显示 
	ENUM_HAL_VALUE_CARLIFE_CAR_TO_MOB_VIDEO_MEG		= 0x11,			//车机端向手机端发送video编码开始情报失败
	ENUM_HAL_VALUE_CARLIFE_TIMER_HEART_BEAT			= 0x12,			//创建车机端检测手机端的心跳的Timer失败
	ENUM_HAL_VALUE_CARLIFE_CONNECT_ANDROID			= 0x13,			//创建Andriod设备连接线程失败
	ENUM_HAL_VALUE_CARLIFE_AND_CHAT_ABNORMAL		= 0x14,			//Andriod手机与车机通信异常
	ENUM_HAL_VALUE_CARLIFE_CONNECT_IOS_WIFI			= 0x15,			//创建IOS设备WiFi连接线程失败
	ENUM_HAL_VALUE_CARLIFE_IOS_SOCKET				= 0x16,			//车机端和IOS手机端Socket连接失败
	ENUM_HAL_VALUE_CARLIFE_UDP_SOCKET				= 0x17,			//创建车机端UDP的Socket失败
	ENUM_HAL_VALUE_CARLIFE_SOCKET_MUX				= 0x18,			//设定Socket为可复用类型失败
	ENUM_HAL_VALUE_CARLIFE_SOCKET_BOARDCAST			= 0x19,			//设定Socket为可广播类型失败
	ENUM_HAL_VALUE_CARLIFE_BIND						= 0x1A,			//bind发生异常
	ENUM_HAL_VALUE_CARLIFE_BOARDCAST_RECV_FAIL		= 0x1B,			//广播地址接收信息异常
	ENUM_HAL_VALUE_CARLIFE_CAR_RECV_UDP_FAIL		= 0x1C,			//车机接收手机端CarLife应用发送的UDP信息异常
	ENUM_HAL_VALUE_CARLIFE_RECV_UDP_NOT_CARLIFE		= 0x1D,			//车机接收的UDP信息不是CarLife应用
	ENUM_HAL_VALUE_CARLIFE_NAVI						= 0x1E,			//Navi提示音输出在Navi提示音的设备创建之前执行
	ENUM_HAL_VALUE_CARLIFE_VR						= 0x1F,			//语音提示音输出在语音提示音的设备创建之前执行
	ENUM_HAL_VALUE_CARLIFE_VIDEO_INIT_FAIL			= 0x20,			//视频输出资源初始化失败
	ENUM_HAL_VALUE_CARLIFE_CARLIFE_LIB				= 0x21,			//创建CarLife Lib对象失败
	ENUM_HAL_VALUE_CARLIFE_VIDEO_CHANNAL			= 0x22,			//创建视频通道线程失败
	ENUM_HAL_VALUE_CARLIFE_CMD_CONTROL				= 0x23,			//创建控制命令通道线程失败
	ENUM_HAL_VALUE_CARLIFE_MEDIA_CHANNAL			= 0x24,			//创建媒体通道线程失败
	ENUM_HAL_VALUE_CARLIFE_VR_CHANNAL				= 0x25,			//创建语音通道线程失败
	ENUM_HAL_VALUE_CARLIFE_MAP_CHANNAL			    = 0x26,			//创建导航通道线程失败
																						
//(app)
//AUX应用程序异常	
	ENUM_HAL_VALUE_AUXAPP_DEVMGR					= 0x01,		//和devmgr通信异常
//BT应用程序异常
	ENUM_HAL_VALUE_BTAPP_SRCMGR_SERVICE_INIT_FAIL = 0x01,		//SrcMgr中间件初始化失败
	ENUM_HAL_VALUE_BTAPP_AUDIO_SERVICE_INIT_FAIL  = 0x02,		//AudioMgr中间件初始化失败
	ENUM_HAL_VALUE_BTAPP_SYSTEM_SERVICE_INIT_FAIL = 0x03,		//System中间件初始化失败
	ENUM_HAL_VALUE_BTAPP_KEY_SERVICE_INIT_FAIL    = 0x04,		//Key中间件初始化失败
	ENUM_HAL_VALUE_BTAPP_MCUCOMM_SERVICE_INIT_FAIL= 0x05,		//McuComm中间件初始化失败
	ENUM_HAL_VALUE_BTAPP_APPMGR_INIT_FAIL         = 0x06,		//AppMgr初始化失败
	ENUM_HAL_VALUE_BTAPP_VIEW_BASE_FAIL           = 0x07,		//Viewbase初始化失败
	ENUM_HAL_VALUE_BTAPP_SHOWWND_FAIL			  = 0x08,		//showwnd执行失败
	ENUM_HAL_VALUE_BTAPP_BT_FILE				  = 0x09,		//蓝牙配置文件打开失败
	ENUM_HAL_VALUE_BTAPP_WIFI_SERVICE_INIT_FAIL   = 0x0A,		//Wifi中间件初始化失败
	ENUM_HAL_VALUE_BTAPP_BTM_INIT_FAIL            = 0x0B,		//蓝牙中间件btm初始化失败
	ENUM_HAL_VALUE_BTAPP_BTP_INIT_FAIL			  = 0x0C,		//蓝牙中间件btp初始化失败
	ENUM_HAL_VALUE_BTAPP_BTA_INIT_FAIL			  = 0x0D,		//蓝牙中间件bta初始化失败
	ENUM_HAL_VALUE_BTAPP_UIWNDMGRWRAPPER		  = 0x0E,		//取得UIWndMgrWrapper失败
//Carlife应用程序异常	
	ENUM_HAL_VALUE_CARLIFEAPP_UIWNDMGRWRAPPER     = 0x01,		//取得UIWndMgrWrapper失败
	ENUM_HAL_VALUE_CARLIFEAPP_GETUIANALYS		  = 0x02,		//取得GetUIAnalysisObj失败
//DVR应用程序异常
	ENUM_HAL_VALUE_DVRAPP_OPEN_VIDEO_FAIL 		  = 0x01,		//打开视频失败
	//ENUM_HAL_VALUE_DVRAPP_SERVICE   = 0x02,					//中间件初始化失败
	//ENUM_HAL_VALUE_DVRAPP_SD_READ   = 0x03,					//SD卡读取错误
	//ENUM_HAL_VALUE_DVRAPP_SD_FORMAT = 0x04,					//SD卡需要格式化
//Factory应用程序异常
	ENUM_HAL_VALUE_FACTORY 						= 0x01, 				//用户模式，工厂模式，MCU版本，CAN版本，蓝牙版本，MPU版本，Uboot版本，OS版本
//Home应用程序异常
	ENUM_HAL_VALUE_HOME_SYSTEM_CONNECT_FAIL 	= 0x01,					//System服务连接失败
	ENUM_HAL_VALUE_HOME_DEVMGR_CONNECT_FAIL 	= 0x02,					//DevMgr服务连接失败
	ENUM_HAL_VALUE_HOME_WIFISE_CONNECT_FAIL 	= 0x03,					//WifiSer服务连接失败
//Music应用程序异常
	ENUM_HAL_VALUE_MUSICAPP_PLAY 				= 0x01,					//播放异常
	ENUM_HAL_VALUE_MUSICAPP_PAUSE 				= 0x02,					//暂停异常
	ENUM_HAL_VALUE_MUSICAPP_STOP 				= 0x03,					//停止异常
	ENUM_HAL_VALUE_MUSICAPP_NEXT_SONG			= 0x04,					//下一曲异常
	ENUM_HAL_VALUE_MUSICAPP_LAST_SONG			= 0x05,					//上一曲异常
	ENUM_HAL_VALUE_MUSICAPP_SPEED 				= 0x06,					//快进异常
	ENUM_HAL_VALUE_MUSICAPP_REWIND_DOWN 		= 0x07,					//快退异常
	ENUM_HAL_VALUE_MUSICAPP_SEEK				= 0x08,					//seek异常
	ENUM_HAL_VALUE_MUSICAPP_ADD_COLLECT			= 0x09,					//添加收藏异常
	ENUM_HAL_VALUE_MUSICAPP_DEL_COLLECT			= 0x0A,					//删除收藏异常
	ENUM_HAL_VALUE_MUSICAPP_DEVICE_LIST			= 0x0B,					//设备列表异常
	ENUM_HAL_VALUE_MUSICAPP_PLAY_TIME			= 0x0C,					//播放时间异常
	ENUM_HAL_VALUE_MUSICAPP_ALBUM_LIST		 	= 0x0D,					//专辑列表异常
	ENUM_HAL_VALUE_MUSICAPP_ARTIST_LIST			= 0x0E,					//艺术家列表异常
	ENUM_HAL_VALUE_MUSICAPP_COMPOSER_LIST		= 0x0F,					//作曲家列表异常
	ENUM_HAL_VALUE_MUSICAPP_SCHOOLS_LIST		= 0x10,					//流派列表异常
	ENUM_HAL_VALUE_MUSICAPP_FOLDER_LIST			= 0x11,					//文件夹列表异常
	ENUM_HAL_VALUE_MUSICAPP_PLAY_WRONG			= 0x12,					//播放出错异常
	ENUM_HAL_VALUE_MUSICAPP_SET_PLAY_MODE		= 0x13,					//设置播放模式异常
	ENUM_HAL_VALUE_MUSICAPP_GET_LIST			= 0x14,					//获取列表异常
	ENUM_HAL_VALUE_MUSICAPP_ADD_DEVICE			= 0x15,					//设备添加异常
	ENUM_HAL_VALUE_MUSICAPP_DEVICE_SCAN_OVER	= 0x16,					//设备扫描结束异常
	ENUM_HAL_VALUE_MUSICAPP_REMOVE_DEVICE		= 0x17,					//设备移除异常
	ENUM_HAL_VALUE_MUSICAPP_DEVICE_SCAN			= 0x18,					//设备扫描异常
	ENUM_HAL_VALUE_MUSICAPP_DEVICE_ADD			= 0x19,					//设备插入异常
	ENUM_HAL_VALUE_MUSICAPP_FAST_PLAY			= 0x1A,					//快速播放异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_APPMGR		= 0x1B,					//连接appmgr异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_AUDIO		= 0x1C,					//连接audiomgr异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_SRCMGR		= 0x1D,					//连接sourcemgr异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_MUSIC_SER	= 0x1E,					//连接music service异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_NFORE_SER	= 0x1F,					//连接nfore device异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_DEVMGR		= 0x20,					//连接devmgr异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_WIFI		= 0x21,					//连接wifi异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_KEY			= 0x22,					//连接key异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_NOTIFY	 	= 0x23,					//连接notify异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_SYSTEM		= 0x24,					//连接system异常
	ENUM_HAL_VALUE_MUSICAPP_CONNECT_AUTOTEST	= 0x25,					//连接autotest异常
//Video应用程序异常	
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_APPMGR		= 0x01,					//连接appmgr异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_SYSTEM		= 0x02,					//连接system异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_DEVMGR		= 0x03,					//连接devmgr异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_WIFI		= 0x04,					//连接wifi异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_SOURCE		= 0x05,					//连接source异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_NFORE_DEV	= 0x06,					//连接nfore device异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_KEY			= 0x07,					//连接key异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_NOTIFY		= 0x08,					//连接notify异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_AUTOTEST	= 0x09,					//连接autotest异常
	ENUM_HAL_VALUE_VIDEOAPP_CONNECT_VIDEO_SER	= 0x0A,					//连接video service异常
	ENUM_HAL_VALUE_VIDEOAPP_STOP				= 0x0B,					//停止异常
	ENUM_HAL_VALUE_VIDEOAPP_PLAY				= 0x0C,					//播放异常
	ENUM_HAL_VALUE_VIDEOAPP_LAST_SONG			= 0x0D,					//上一曲异常
	ENUM_HAL_VALUE_VIDEOAPP_NEXT_SONG			= 0x0E,					//下一曲异常
	ENUM_HAL_VALUE_VIDEOAPP_PAUSE				= 0x0F,					//暂停异常
	ENUM_HAL_VALUE_VIDEOAPP_SPEED				= 0x10,					//快进异常
	ENUM_HAL_VALUE_VIDEOAPP_REWINDDOWN			= 0x11,					//快退异常
	ENUM_HAL_VALUE_VIDEOAPP_SEEK				= 0x12,					//seek异常
	ENUM_HAL_VALUE_VIDEOAPP_PLAY_TIME			= 0x13,					//播放时间异常
	ENUM_HAL_VALUE_VIDEOAPP_PLAY_WRONG			= 0x14,					//播放出错异常
	ENUM_HAL_VALUE_VIDEOAPP_LIST				= 0x15,					//列表异常
	ENUM_HAL_VALUE_VIDEOAPP_FOLDER				= 0x16,					//文件夹列表异常
	ENUM_HAL_VALUE_VIDEOAPP_PLAY_MODE			= 0x17,					//播放模式异常
	ENUM_HAL_VALUE_VIDEOAPP_SCAN_OVER			= 0x18,					//扫描完成异常
	ENUM_HAL_VALUE_VIDEOAPP_ADD_DEV				= 0x19,					//设备添加异常
	ENUM_HAL_VALUE_VIDEOAPP_REMOVE_DEV			= 0x1A,					//设备移除异常
	ENUM_HAL_VALUE_VIDEOAPP_SCAN_OVER_T			= 0x1B,					//扫描完成异常
	ENUM_HAL_VALUE_VIDEOAPP_FAST_PLAY			= 0x1C,					//快速播放异常
	ENUM_HAL_VALUE_VIDEOAPP_INSERT_DEV			= 0x1D,					//设备插入异常
//Picture应用程序异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_APPMGR		= 0x01,					//连接appmgr异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_DEVMGR		= 0x02,					//连接devmgr异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_WIFI			= 0x03,					//连接wifi异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_SOURCE		= 0x04,					//连接source异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_NFORE			= 0x05,					//连接nfore device异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_NOTIFY		= 0x06,					//连接notify异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_KEY			= 0x07,					//连接key异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_SYSTEM		= 0x08,					//连接system异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_PIC			= 0x09,					//连接picture异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_FOLDER_LIST	= 0x0A,					//文件夹列表异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_SCAN_OVER		= 0x0B,					//扫描完成异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_ADD_DEV		= 0x0C,					//设备添加异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_REMOVE_ADD	= 0x0D,					//设备移除异常
	ENUM_HAL_VALUE_PICTUREAPP_CONNECT_FAST_PLAY		= 0x0E,					//快速播放异常
//Radio应用程序异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_APPMGR			= 0x01,					//连接appMgr异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_AUDIOMGR		= 0x02,					//连接audiomgr异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_DEVMGR			= 0x03,					//连接devmgr异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_WIFI			= 0x04,					//连接wifi异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_SOURCE			= 0x05,					//连接source异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_RADIO			= 0x06,					//连接radio service异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_KEY				= 0x07,					//连接key异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_NOTIFY			= 0x08,					//连接notify异常
	ENUM_HAL_VALUE_RADIOAPP_CONNECT_SYSTEM			= 0x09,					//连接system异常
//Setting应用程序异常
	ENUM_HAL_VALUE_SETTING_SYSTEMSER_CONNECT_FAIL 	= 0x01,		//System服务连接失败
	ENUM_HAL_VALUE_SETTING_DERMGRSER_CONNECT_FAIL	= 0x02,		//DevMgr服务连接失败
	ENUM_HAL_VALUE_SETTING_WIFISER_CONNECT_FAIL  	= 0x03,  	//WifiSer服务连接失败
	ENUM_HAL_VALUE_SETTING_GET_DATA_FAIL          	= 0x04,   	//从SettingService获取数据失败
	ENUM_HAL_VALUE_SETTING_SET_DATA_FAIL   		  	= 0x05,  	//向SettingService设置数据失败
	ENUM_HAL_VALUE_SETTING_CREATE_PTHREAD_FAIL    	= 0x06,		//耗时线程创建失败
	ENUM_HAL_VALUE_SETTING_GETAUDIO_FAIL  		 	= 0x07,		//从AudioMgr获取当前声道失败
	ENUM_HAL_VALUE_SETTING_GETMSG_FROM_DEVMGR_FAIL  = 0x08, 	//从DeviceMgr获取当前设备信息失败
	ENUM_HAL_VALUE_SETTING_SET_EQ   				= 0x09,		//设置Eqvalue失败
	ENUM_HAL_VALUE_SETTING_SET_FADE_BALAN_FAIL  	= 0x0A,		//设置fade/balance失败
	ENUM_HAL_VALUE_SETTING_SET_CHARGE_FAIL 			= 0x0B,		//设置充电模式失败
	ENUM_HAL_VALUE_SETTING_GET_MCU_VER_FAIL			= 0x0C,		//获取MCU版本失败
	ENUM_HAL_VALUE_SETTING_GET_WIFI_SCAN_FAIL		= 0x0D,		//获取WIFI扫描结果失败
	ENUM_HAL_VALUE_SETTING_WIFI_OPEN_FAIL			= 0x0E,		//WIFI打开失败
	ENUM_HAL_VALUE_SETTING_WIFI_CLOSE_FAIL			= 0x0F,		//WIFI关闭失败
	ENUM_HAL_VALUE_SETTING_WIFI_CON_CALL_FAIL       = 0x10,		//WIFI连接调用失败
	ENUM_HAL_VALUE_SETTING_WIFI_DISCON_CALL_FALIL   = 0x11,		//WIFI断开调用失败
	ENUM_HAL_VALUE_SETTING_WIFI_SCAN_FAIL			= 0x12,		//WIFI开始扫描失败
//Overlay应用程序异常
	ENUM_HAL_VALUE_OVERLAY_RADAR			= 0x01				//雷达通信故障
	//ENUM_HAL_VALUE_OVERLAY_INIT_FAIL		= 0x02			//中间件初始化失败

	
//根据新添加的故障码值添加故障码参数...

}CONFIG_DIAGNOSIS_PARA;


#endif